[package]
name = "ezhttp"
version = "0.1.0"
edition = "2021"

repository = "https://github.com/MeexReay/ezhttp"
description = "lightweight http server"
license-file = "LICENSE"
readme = "README.md"
keywords = ["http", "server", "site"]

[dependencies]
urlencoding = "2.1.3"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
